### ISSUE TITLE
Payload of attack

### ISSUE THREAD

**Issue by L3V14TH4N** [zecure/shadowd#12]
hello, how do you view the payload of the attack in post method? for example in: https://demo.shadowd.zecure.org/blacklist/rules?blacklist_rule_filter[searchCallers][0]=/var/www/blog/wp-admin/post.php

**Comment by zit-hb** [comment]
Hi.

I am not sure I understand the question right. You can see the parameters of captured attacks here: https://demo.shadowd.zecure.org/parameters

That includes post parameters: https://demo.shadowd.zecure.org/parameters?parameter_filter[searchPaths][0]=POST|*

Values get cut off after 50 chars, so that they don't break the table. If you want to see the full payload you have to click on the magnifying glasses, for example: https://demo.shadowd.zecure.org/parameter/37893

Best regards,
Hendrik

**Comment by L3V14TH4N** [comment]
Hi.. Sorry! I did not pay attention to the options parameter...

**Comment by zit-hb** [comment]
Alright, no problem. I have restructured the menu in version 2.0 to make this more clear. I will release it in some hours :)
