### ISSUE TITLE
I am interested in writing a middleware for Golang HTTP services that will act as a connector.

### ISSUE THREAD

**Issue by elico** [zecure/shadowd#15]
Hey I started looking on the way the php and the other connectors are implemented and I think it will be pretty simple for me to write a basic beta connector that will only send he events to the shadowd service.
I was wondering about resources that can help me to do that.

Thanks,

**Comment by zit-hb** [comment]
Hey elico.

Sounds very nice. I am not familiar with web applications written in Go, so I can't say too much about that specifically, but there are two resources that should help a lot. For one the documentation of the [network protocol](https://shadowd.zecure.org/documentation/architecture/#protocol:1bf455b3a3c6e1e40be41ef6023b75eb) and the documentation of the [connectors](https://shadowd.zecure.org/documentation/connectors/). I try to keep the configurations and error messages of the different connectors as similar as possible.

All in all it should be not too hard. The protocol is easy and the amount of work a connector has to do is low. One thing you have to remember is to [escape](https://github.com/zecure/shadowd_python/blob/v2.0.0/shadowd/django_connector.py#L40) and [unescape](https://github.com/zecure/shadowd_python/blob/v2.0.0/shadowd/django_connector.py#L94) the path keys.

If you have problems or other questions don't hesitate to ask.

Best regards,
Hendrik

**Comment by elico** [comment]
I wrote some code but something not working fine and I am not sure what.
Some sketch code at: https://gist.github.com/elico/ec9768dfb62e8530c130
The result is something like:
2
c160105cb6c45e0b86f7d22ddc12b4868c211015eecdf988260e353fb2bae489
{"caller":"\/1.txt","client-ip":"192.168.10.192","hashes":{"sha256":"7585d19b99688a63dbaae188ace681d13e7aa825fa59a93403b7cea1a88bd8b2"},"input":{"SERVER|HTTP_ACCEPT":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,*\/*;q=0.8,MoreCache\/Override","SERVER|HTTP_ACCEPT_LANGUAGE":"en-US,en;q=0.5","SERVER|HTTP_CACHE_CONTROL":"max-age=0","SERVER|HTTP_CONNECTION":"keep-alive","SERVER|HTTP_COOKIE":"","SERVER|HTTP_HOST":"192.168.10.168","SERVER|HTTP_IF_MODIFIED_SINCE":"Wed, 27 Jan 2016 15:21:03 GMT","SERVER|HTTP_PORT":"8090","SERVER|HTTP_REFERER":"http:\/\/192.168.10.168:8090\/","SERVER|HTTP_USER_AGENT":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64; rv:43.0) Gecko\/20100101 Firefox\/43.0 Cyberfox\/43.0.4"},"resource":"\/1.txt","version":"2.0.1-go"}
reply from server= {"status":1,"threats":[]}

But I am not sure what is cause the logs to not apear under the profile.

**Comment by zit-hb** [comment]
It is `client_ip`, not `client-ip`. So [this](https://github.com/zecure/shadowd/blob/v2.0.0/src/request_handler.cpp#L112-L116) fails. Other than that the json-data looks good.

The `escapeKey` and `unescapeKey` usage in the code does not seem to be correct yet. Caller, resource and values do not have to be escaped, only the single parts of paths, e.g. the `k` in [this](https://gist.github.com/elico/ec9768dfb62e8530c130#file-golang-simple-shadowd-connector-L55-L59): `inputmap[req.Method+"|"+escapeKey(k)] = s`

The reason for this requirement are associative input arrays. Not every language or framework has them, but PHP for instance does. As a result of that all languages have to escape the paths, even if they do not support associative input arrays. By escaping the pipe symbol we make sure that e.g. test[foo][bar] is not the same as test[foo|bar] in the internal representation of Shadow Daemon. Otherwise test.php?test[foo|bar]=evil&test[foo][bar]=23 could be used to bypass the firewall.

Another thing I noticed, you should not modify the paths (except of escaping it). So better not replace scores with underscores, make it uppercase and stuff like that. The path should be an exact representation of it's internal state. Here is an example why this is important: if you send the headers `foo-bar` and `foo_bar` both turn into `FOO_BAR` and only one of them is saved in the map and send to shadowd, but the web application receives both.

I think `net/http` in Golang is not CGI-like, so the [integrity check](https://shadowd.zecure.org/documentation/integrity/) does not make sense. Just send an empty map for `hashes`. No need to fill it. It has to exist though.

All in all pretty nice work already :)

**Comment by elico** [comment]
Just wanted to let you know I wrote a golang http connector which works at:
https://github.com/elico/go-shadowd

**Comment by zit-hb** [comment]
Nice. Btw. the escaping applies to all paths, i.e.
 * https://github.com/elico/go-shadowd/blob/master/go-shadowd.go#L86 `inputmap["COOKIE|"+escapeKey(v.Name)] = v.Value`
 * https://github.com/elico/go-shadowd/blob/master/go-shadowd.go#L99 `inputmap["SERVER|"+escapeKey(k)] = strings.Join(v, "")`

Adding `SERVER|HTTP_COOKIE` manually is really not necessary.

**Comment by elico** [comment]
OK, I wasn't sure about the escaping.
And I see that you didn't mentioned the `strings.ToUpper(k)` and I am unsure if it means anything.
I upper case it since there is no meaning what so ever from the go http server side for these headers(the service is RFC compliance).
About the cookies ToUpper, I have seen that this is what is being done on the other modules but I am not sure if there is an RFC that states that a cookie name upper and lower should not matter and treated the same.
I will change: 

- https://github.com/elico/go-shadowd/blob/master/go-shadowd.go#L99

But I will need to read the RFC for the cookies.

About the addition of the `SERVER|HTTP_COOKIE` I have seen something related in some of the outputs some I am not sure about it.
For now I will add a Boolean for this option since It can help in debugging some issues.

If you noticed or not I wrote this ICAP service:
- https://github.com/elico/go-shadowd/blob/master/examples/icap-squid-to-waf.go

Which basically is being used as a squid caching related requests analysis and logging tool, it helps to identify what in the requests properties of users\clients results in unique responses and by that it can help to determine the right requests mangling rules in other services

**Comment by zit-hb** [comment]
I did not find anything about case insensitivity related to cookie names in RFC 6265. At least PHP treats them differently:

    <?php
    var_dump($_COOKIE);
    
    array (size=2)
      'foo' => string 'bar' (length=3)
      'FOO' => string 'BAR' (length=3)

My stance on this is, as I said earlier, don't modify the keys/names unless there is a very good reason to do so. Replacing characters in the names just makes the logs and the analysis less meaningful, because it strips away information that may be important in some cases. The advantage of Shadow Daemon compared to other wafs (that parse the HTTP data themselves) is that the analyzed user input is exactly the same as the one that the web application receives. Which is not really the case anymore if you modify it before sending it to shadowd. The important thing is not what the RFC states, but what the web application (or more precise, the web lib/framework that the application is using) is doing. After all, it is possible that the lib/framework does not fully comply to the RFC or handles unspecified edge cases differently than expected.

About the `SERVER|HTTP_COOKIE`: If you use CGI this header is in the environment of the web application. So e.g. in PHP you have this input, true. But you don't gain anything by constructing it manually and appending it. After all, it does not reflect the original user input exactly and the parsed cookies are already added via `COOKIE|`.

ICAP looks interesting. Haven't used it yet, but a plugin for that may turn out useful.

**Comment by elico** [comment]
I didn't read the full shadowd documentation so I don't know and I if there is a way in shadowd to treat the name without case sensitivity as a part of the rule it's another story and I would prefer to not change the original value casing.

**Comment by zit-hb** [comment]
It is not possible to have case-insensitive rules in shadowd yet. Maybe a good idea for later versions.

> I would prefer to not change the original value casing.

I don't get this part. That is exactly what you are doing by applying `ToUpper` and what I recommend not to do.

**Comment by elico** [comment]
This is what I am doing now but when I wrote the code I was considering to not upper case them and eventually wrote the code as it is.
For now I will use a boolean and by default enable the upper casing, if someone wants it otherwise he will be able to.

I will run a small test with shadowd in learning mode to log the requests and see how cookies looks like in most standard applications such as wordpress and others php based, ASP apps, cloudflare, akamai, Golang web services etc (if you have suggestions for test subjects I am open).
