### ISSUE TITLE
Monitoring multiple servers/apps with one shadowd instance

### ISSUE THREAD

**Issue by viktorix** [zecure/shadowd#29]
I'm curious, is it possible to run one instance of shadowd that would monitor multiple servers/apps? Similar to how OSSEC works with agents on multiple servers.

**Comment by zit-hb** [comment]
Yes, that is totally possible. If you want to run multiple applications with the same web server you can use [environment variables](https://shadowd.zecure.org/overview/php_connector/#configuration:e68121fd6d9611f95298531fbbf8157d) to specify different configuration files for every vhost. Since shadowd is exposed through a TCP port you can connect web applications from anywhere in the world to your instance, though I would not recommend to run shadowd in China if your web application is in the States, latency might get a bit too high.

**Comment by zit-hb** [comment]
Since the question is answered I will close this now.
