### ISSUE TITLE
Issue configuring Shadowd

### ISSUE THREAD

**Issue by yghazi** [zecure/shadowd#4]
Hi, 

I'm interested in the shadowd project. I think the concept is great, and I wanted to check out the code and run it for myself. Having followed the installation and configuration instructions, I deployed shadowd and a PHP web app in front, and I set it to be learning-enabled. However, it doesn't show me any activity whatsoever. The database is empty, no parameters or requests are being recorded. Can you help me out with this and tell me where I'm wrong?

Thanks,
YG

**Comment by zit-hb** [comment]
Hi yghazi,

thanks for the interest. Are you sure that the connector is loaded? You can check it by opening `<?php phpinfo(); ?>` and looking at `auto_prepend_file`. Other than that, learning requests are not showed by default in the web interface. You have to click on the gears first and then change *learning* to *enabled*.

Best regards,
Hendrik

**Comment by yghazi** [comment]
Hey Hendrik,

Thanks for the quick response. I appreciate it. To answer your question, yes, the connector is being loaded. In fact, it was having a parsing issue and I had to fix that. I had assumed that when I set the profile to learning mode, I was going to at least see some parameters being added to the database, and later based on those parameters, I would be able to generate rules. Am I wrong? 

I actually want to use shadowd as a web honeypot and I toggled the "observe" value in connectors.ini to 1. And in order to test it, I put up DVWA with apache2 on Ubuntu 14.04. But I don't see anything that suggests whether the backend shadowd server is running, although netstat confirms that it is. There are no errors in log either. I'm out of my depth, here. Please advise. In the mean time, I will try to click on the gears, like you said and hope for a miracle.

Best,
YG

**Comment by zit-hb** [comment]
Oh, that explains a lot. If you turn on *observe* the connector will not stop when something critical happens. So I guess the connector does not have the right permissions to read the configuration file or something along these lines. You can find out if this is the case by enabling *debug* in */etc/shadowd/connectors.ini*. This writes warnings and errors to the error log of your web server. Also make sure that you have set the right *id* and *key* in *connectors.ini*, otherwise it will not connect to shadowd.

You got the part about the learning mode right at the beginning, that is how it works. The problem with DSL is that there will not be any legitimate requests. This makes the default learning data not very good, so if you want to generate whitelist rules you will probably also have to visit the site by your own and use it non-malicious to fill up the data reservoir.
Luckily the blacklist will detect probably all attacks and a lot of the probings. Don't get me wrong, the whitelist has some great advantages like detecting single char probings, backdoors etc., but dependent on the software target it can also be a lot of work to set it up from scratch. On the other hand, DVWA does not look very huge in regards to sites and parameters, so it should not be too much work to just modify the whitelist rules by hand that the generator did not get right, because of the noisy learning data.
If you set the default blacklist threshold to a low value (0 maybe, or 5 if you have too many false positives) the smallest sign of an attack will trigger the detection system, so the results will be good.

**Comment by zit-hb** [comment]
There was no response in almost a month, so I consider this done.
