### ISSUE TITLE
not blocking XSS

### ISSUE THREAD

**Issue by alonf1983** [zecure/shadowd#53]
Hi 
I have setup the WAF to "Active" and i can see the requests, however it is not blocked malious payload (XSS)

![image](https://user-images.githubusercontent.com/33452418/110600450-9cbd7a80-818c-11eb-874c-3a415fef378a.png)

for example:

![image](https://user-images.githubusercontent.com/33452418/110600284-70a1f980-818c-11eb-8412-f28549284cc4.png)

**_http://AAA.BBB/bwapp/htmli_get.php?firstname=%3Cscript%3Ealert%281%29%3C%2Fscript%3E&lastname=%3Cscript%3Ealert%281%29%3C%2Fscript%3E&form=submit_**

![image](https://user-images.githubusercontent.com/33452418/110600246-64b63780-818c-11eb-924e-1fd996e4bb96.png)

could you tell me where i worng?

Thanks

**Comment by zit-hb** [comment]
Hey! Have a look in the error log of your web server, it should contain more details. Likely the configuration file is not readable by your web server user or the profile id/key are incorrect.

**Comment by zit-hb** [comment]
Hey! The request was logged, so I assume something was detected? Can you post a screenshot of the `parameters` page?

FYI, if a threat is detected in a parameter by the blacklist only that parameter is removed from the request but the request is not blocked.

**Comment by zit-hb** [comment]
Also, the default blacklist threshold in the profile is quite high. I choose it so that there are not a lot of false-positives by default. For the best results I highly recommend to use a low value like 3 for it and then create single blacklist rules for properties that tend to have a higher value without being malicious. A more detailed explanation is available here: https://shadowd.zecure.org/tutorials/rules/

**Comment by zit-hb** [comment]
There hasn't been any activity in over a month, so I am going ahead and closing this issue.

**Comment by mareksoha** [comment]
Hello @zit-hb .
May I know why you decided to not block whole request but to cut out only the "weird" part of it? 
I don't want this requests to flow through and reach the backend. Can you let me know what to change to block it completely?
Many thanks.

**Comment by mareksoha** [comment]
@zit-hb thanks, it seems to be working...
1) Is it possible to send also some different HTTP response code instead of 200? eg. 403.
2) I am getting mixed results with this URL:
new_api/?select%20*%20from%20a%20where%201=1
I want to parse it and get it blocked but with GET|\bselect\b it is blocking it only when it is in form ?id=select ....
Any idea here?
Thanks.

**Comment by zit-hb** [comment]
@mareksoha 
1. Only by modifying the code of the `error` function.
2. The blacklist does not check the path of the input. If the whitelist is enabled, the "unknown" path will be rejected. I will think about scanning the path with blacklist too though.

**Comment by mareksoha** [comment]
@zit-hb can you get in touch with me please? Here or google my username. I'd like some changes to be done and want to do it on b2b basis. I can't get ahold of anybody who would be able to do it...
Thanks.

**Comment by zit-hb** [comment]
@mareksoha I am not interested in commissioned work. If you have feature requests feel free to create issues (one feature request per issue) and if I think it is a valuable change that everyone benefits from, I might actually implement it.
